

const  responseV2 ={
    status:200,
    data:JSON.parse(JSON.stringify([
        {
            "placementId": 8441575,
            "placementStartDate": null,
            "placementEndDate": null,
            "placementDuration": null,
            "facility": {
                "facilityId": 467262,
                "facilityName": "California Hospital Medical Center - CommonSpirit",
                "facilityAddress1": "1401 S. GRAND AVE.",
                "facilityAddress2": null,
                "facilityState": "CA",
                "facilityCity": "LOS ANGELES",
                "facilityCounty": "Los Angeles",
                "facilityZip": 90015,
                "facilityLongitude": -118.265616,
                "facilityLatitude": 34.039429,
                "facilityCountry": "USA",
                "facilityRegionId": 119,
                "facilityRegion": "West Coast"
            },
            "travelerId": 1214223,
            "candidateNameFirst": "Justin",
            "candidateNameMiddle": null,
            "candidateNameLast": "Edelen",
            "candidateNameGoesBy": null,
            "brandId": 1,
            "brand": "AMN Nurse",
            "amnDivisionTypeId": 3,
            "amnDivisionType": "AMN Nurse",
            "orderId": 1069370,
            "orderTypeId": 1,
            "orderType": "Travel",
            "disciplineId": 36,
            "specialtyId": 87,
            "subspecialtyId": 0,
            "shiftId": null,
            "shift": null,
            "payCycleStartDayNum": 1,
            "payCycleStartDay": "Sunday",
            "payCycleEndDayNum": 7,
            "payCycleEndDay": "Saturday",
            "isPerDiemValuesValid": true,
            "isScenarioExtention": false,
            "extensionNumber": 1,
            "isExtensionOfPriorPlacement": false,
            "extensionOfPriorPlacementId": null,
            "bookingPeriodId": 379,
            "bookingPeriodStartDate": "2020-10-15T23:59:59",
            "bookingPeriodEndDate": "2021-01-13T23:59:59",
            "bookingPeriodDuration": 13,
            "packageName": "Assignment",
            "recruiter": {
                "employeeId": 6986,
                "firstName": "Christina",
                "lastName": "Gonzalez",
                "phoneNumber": "(858) 465-2653",
                "email": "Christina.Gonzalez@amnhealthcare.com"
            },
            "accountManager": {
                "employeeId": 6567,
                "firstName": "Chelsea",
                "lastName": "Hamilton",
                "phoneNumber": "(858) 720-6263",
                "email": "Chelsea.Hamilton@amnhealthcare.com"
            },
            "isMostRecentBookingPeriod": true,
            "candidateSkillSets": [
                {
                    "disciplineId": null,
                    "disciplineAbbr": null,
                    "specialtyId": null,
                    "specialtyAbbr": null,
                    "subSpecialtyId": null,
                    "subSpecialtyAbbr": null,
                    "status": "Hearsay"
                },
                {
                    "disciplineId": 36,
                    "disciplineAbbr": "SPT",
                    "specialtyId": 87,
                    "specialtyAbbr": "Sterile Processor",
                    "subSpecialtyId": null,
                    "subSpecialtyAbbr": null,
                    "status": "Verified"
                }
            ],
            "scenarios": [
                {
                    "placementId": 8441575,
                    "bookingPeriodId": 379,
                    "scenarioId": 639,
                    "scenarioName": "Scenario 1",
                    "scenarioStatusId": 1,
                    "scenarioStatus": "Pending",
                    "tla": false,
                    "createdUserId": 15568,
                    "createdUserFirst": "Anil",
                    "createdUserLast": "Bhasi",
                    "createdDateAt": "2024-10-22T17:20:20.983",
                    "updatedUserId": 15568,
                    "updatedUserFirst": "Anil",
                    "updatedUserLast": "Bhasi",
                    "updatedDateAt": "2024-10-23T14:29:00.803",
                    "grossMargin": null,
                    "grossProfit": null,
                    "negotiatedContributionMargin": null,
                    "approvedUserId": null,
                    "approvedUserFirst": null,
                    "approvedUserLast": null,
                    "approvedDateAt": null,
                    "approvedReasonId": null,
                    "verifiedUserId": null,
                    "verifiedUserFirst": null,
                    "verifiedUserLast": null,
                    "verifiedDateAt": null,
                    "verifiedReasonId": null,
                    "notes": null,
                    "payCycleStartDayNum": 1,
                    "payCycleStartDay": "Sunday",
                    "payCycleEndDayNum": 7,
                    "payCycleEndDay": "Saturday",
                    "isPerDiemValuesValid": true,
                    "interimPayPackageTimeOffId": null,
                    "assignment": {
                        "timeOffs": [],
                        "travel": {
                            "arrivingTravel": 250,
                            "arrivalAmountPerMile": 0.67,
                            "endingTravel": 250,
                            "endingAmountPerMile": 0.67,
                            "interimTravel": null,
                            "interimAmountPerMile": null,
                            "amnFlight": null,
                            "amnRentalCar": null
                        },
                        "payPackageDetailsValues": []
                    },
                    "timestamp": "0x00000001CF5F7887",
                    "isDefaultScenario": false,
                    "isMostRecentBookingPeriod": true,
                    "splits": [
                        {
                            "placementId": 8441575,
                            "bookingPeriodId": 379,
                            "scenarioId": 639,
                            "splitId": 724,
                            "effectiveStartDate": "2020-10-15T23:59:59",
                            "effectiveEndDate": "2025-01-11T00:00:00",
                            "payCycleStartDayNum": 1,
                            "payCycleStartDay": "Sunday",
                            "payCycleEndDayNum": 7,
                            "payCycleEndDay": "Saturday",
                            "splitStartDayNum": 5,
                            "splitStartDay": "Thursday",
                            "splitEndDayNum": 7,
                            "splitEndDay": "Saturday",
                            "isPerDiemValuesValid": true,
                            "billRate": 58.55,
                            "overtime": 0,
                            "holiday": 0,
                            "callback": 0,
                            "billGuaranteedHours": 40,
                            "billAmountPerMile": 0,
                            "payAmountPerMile": 0.67,
                            "splitPlacementId": null,
                            "housingCoPay": null,
                            "lodgingPerDiem": 101.26027,
                            "standardFurniture": null,
                            "housingTypeId": 1,
                            "housingType": "No Housing",
                            "earlyMoveInDays": null,
                            "earlyMoveInDaysWaived": null,
                            "earlyMoveInCostPerDay": null,
                            "lateMoveOutDays": null,
                            "lateMoveOutDaysWaived": null,
                            "lateMoveOutCostPerDay": null,
                            "mealPerDiem": 50,
                            "cellPhoneStipend": 1,
                            "tlaMealAllowance": 30,
                            "tlaCarAllowance": 50,
                            "tlaShiftCompletionBonus": null,
                            "shiftId": 1,
                            "shift": "12 D",
                            "hoursPerWeek": 36,
                            "hoursPerShift": 12,
                            "healthInsuranceTypeId": 1,
                            "healthInsuranceType": "Accepted",
                            "isWaitingPeriodBenefit": false,
                            "tlaCellPhoneStipend": 1,
                            "vms": 6,
                            "other": 1.87,
                            "billDoubletimeRate": 0,
                            "billOvertimeFactor": 1,
                            "billCallBackFactor": 0,
                            "billDoubletimeFactor": 1,
                            "billHolidayFactor": 0.22,
                            "billOnCallRate": 7,
                            "billCharge": 5,
                            "billPreceptor": 0,
                            "orientationHours": 12,
                            "isVoidOrientationHours": null,
                            "payRate": 17.29,
                            "minPayRate": 17.29,
                            "payOvertimeFactor": 1.5,
                            "payCallBackFactor": 0,
                            "payDoubletimeFactor": 2,
                            "payHolidayFactor": 0.3,
                            "payOnCallRate": 3.5,
                            "payGuaranteedHours": 0,
                            "payCharge": 19.78,
                            "payPreceptor": 0,
                            "csfSupervisorCosts": 0,
                            "additionalCostMiscellaneousAmount": null,
                            "additionalCostMiscellaneousDescription": null,
                            "furnitureCoPay": null,
                            "isEarlyMoveIn": null,
                            "isLateMoveOut": null,
                            "earlyMoveInDate": null,
                            "lateMoveOutDate": null,
                            "rentCost": null,
                            "utilities": null,
                            "rentOverrideNot": null,
                            "miscellaneousFurnitureDescription": null,
                            "orientationFactor": 1,
                            "orientationRate": 0,
                            "orientationOverrideUserId": null,
                            "orientationOverrideFirst": null,
                            "orientationOverrideLast": null,
                            "orientationOverrideDate": null,
                            "standardFurnitureOriginal": null,
                            "utilitiesOriginal": null,
                            "rentCostOriginal": null,
                            "furnitureCosts": [
                                {
                                    "id": 19,
                                    "description": "Sofa bed",
                                    "standardCost": 20,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 20,
                                    "description": "TV Stand",
                                    "standardCost": 0,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 22,
                                    "description": "TV - 25 inch",
                                    "standardCost": 30,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 23,
                                    "description": "Extra TV Stand",
                                    "standardCost": 10,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 24,
                                    "description": "Microwave",
                                    "standardCost": 10,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 25,
                                    "description": "DVD Player",
                                    "standardCost": 15,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 26,
                                    "description": "Computer Desk/Chair",
                                    "standardCost": 40.5,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 28,
                                    "description": "Recliner",
                                    "standardCost": 40,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 29,
                                    "description": "Queen Size Bed",
                                    "standardCost": 0,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 30,
                                    "description": "Twin Beds (2)",
                                    "standardCost": 20,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 31,
                                    "description": "King Size Bed",
                                    "standardCost": 20,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 38,
                                    "description": "Additional Bedroom Set",
                                    "standardCost": 75,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 32,
                                    "description": "Washer/Dryer",
                                    "standardCost": 65,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 33,
                                    "description": "Vacuum",
                                    "standardCost": 23,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 34,
                                    "description": "Housewares Package (free to TTS only)",
                                    "standardCost": 155,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 35,
                                    "description": "Miscellaneous One",
                                    "standardCost": 0,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 36,
                                    "description": "Miscellaneous Two",
                                    "standardCost": 0,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 37,
                                    "description": "Miscellaneous Three",
                                    "standardCost": 0,
                                    "costToTraveler": null,
                                    "quantity": 0
                                }
                            ],
                            "moveInDate": "2020-10-13T23:59:59",
                            "moveOutDate": "2021-01-15T23:59:59",
                            "standardMinPayRate": null,
                            "standardNewGradPayRate": null,
                            "standardTLAMinPayRate": null,
                            "standardTLANewGradPayRate": null,
                            "standardTeletherapy": null,
                            "isAlliedTrue": false,
                            "isAssignmentSplit": true
                        },
                        {
                            "placementId": 8441575,
                            "bookingPeriodId": 379,
                            "scenarioId": 639,
                            "splitId": 725,
                            "effectiveStartDate": "2024-10-17T00:00:00",
                            "effectiveEndDate": "2021-01-13T23:59:59",
                            "payCycleStartDayNum": 1,
                            "payCycleStartDay": "Sunday",
                            "payCycleEndDayNum": 7,
                            "payCycleEndDay": "Saturday",
                            "splitStartDayNum": 5,
                            "splitStartDay": "Thursday",
                            "splitEndDayNum": 7,
                            "splitEndDay": "Wednesday",
                            "isPerDiemValuesValid": true,
                            "billRate": 58.55,
                            "overtime": 0,
                            "holiday": 0,
                            "callback": 0,
                            "billGuaranteedHours": 40,
                            "billAmountPerMile": 0,
                            "payAmountPerMile": 0.67,
                            "splitPlacementId": null,
                            "housingCoPay": null,
                            "lodgingPerDiem": 101.26027,
                            "standardFurniture": null,
                            "housingTypeId": 1,
                            "housingType": "No Housing",
                            "earlyMoveInDays": null,
                            "earlyMoveInDaysWaived": null,
                            "earlyMoveInCostPerDay": null,
                            "lateMoveOutDays": null,
                            "lateMoveOutDaysWaived": null,
                            "lateMoveOutCostPerDay": null,
                            "mealPerDiem": 50,
                            "cellPhoneStipend": 1,
                            "tlaMealAllowance": 30,
                            "tlaCarAllowance": 50,
                            "tlaShiftCompletionBonus": null,
                            "shiftId": 1,
                            "shift": "12 D",
                            "hoursPerWeek": 36,
                            "hoursPerShift": 12,
                            "healthInsuranceTypeId": 1,
                            "healthInsuranceType": "Accepted",
                            "isWaitingPeriodBenefit": false,
                            "tlaCellPhoneStipend": 1,
                            "vms": 6,
                            "other": 1.87,
                            "billDoubletimeRate": 0,
                            "billOvertimeFactor": 1,
                            "billCallBackFactor": 0,
                            "billDoubletimeFactor": 1,
                            "billHolidayFactor": 0.22,
                            "billOnCallRate": 7,
                            "billCharge": 5,
                            "billPreceptor": 0,
                            "orientationHours": 12,
                            "isVoidOrientationHours": null,
                            "payRate": 17.29,
                            "minPayRate": 17.29,
                            "payOvertimeFactor": 1.5,
                            "payCallBackFactor": 0,
                            "payDoubletimeFactor": 2,
                            "payHolidayFactor": 0.3,
                            "payOnCallRate": 3.5,
                            "payGuaranteedHours": 0,
                            "payCharge": 19.78,
                            "payPreceptor": 0,
                            "csfSupervisorCosts": 0,
                            "additionalCostMiscellaneousAmount": null,
                            "additionalCostMiscellaneousDescription": null,
                            "furnitureCoPay": null,
                            "isEarlyMoveIn": null,
                            "isLateMoveOut": null,
                            "earlyMoveInDate": null,
                            "lateMoveOutDate": null,
                            "rentCost": null,
                            "utilities": null,
                            "rentOverrideNot": null,
                            "miscellaneousFurnitureDescription": null,
                            "orientationFactor": 1,
                            "orientationRate": 0,
                            "orientationOverrideUserId": null,
                            "orientationOverrideFirst": null,
                            "orientationOverrideLast": null,
                            "orientationOverrideDate": null,
                            "standardFurnitureOriginal": null,
                            "utilitiesOriginal": null,
                            "rentCostOriginal": null,
                            "furnitureCosts": [
                                {
                                    "id": 19,
                                    "description": "Sofa bed",
                                    "standardCost": 20,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 20,
                                    "description": "TV Stand",
                                    "standardCost": 0,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 22,
                                    "description": "TV - 25 inch",
                                    "standardCost": 30,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 23,
                                    "description": "Extra TV Stand",
                                    "standardCost": 10,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 24,
                                    "description": "Microwave",
                                    "standardCost": 10,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 25,
                                    "description": "DVD Player",
                                    "standardCost": 15,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 26,
                                    "description": "Computer Desk/Chair",
                                    "standardCost": 40.5,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 28,
                                    "description": "Recliner",
                                    "standardCost": 40,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 29,
                                    "description": "Queen Size Bed",
                                    "standardCost": 0,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 30,
                                    "description": "Twin Beds (2)",
                                    "standardCost": 20,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 31,
                                    "description": "King Size Bed",
                                    "standardCost": 20,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 38,
                                    "description": "Additional Bedroom Set",
                                    "standardCost": 75,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 32,
                                    "description": "Washer/Dryer",
                                    "standardCost": 65,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 33,
                                    "description": "Vacuum",
                                    "standardCost": 23,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 34,
                                    "description": "Housewares Package (free to TTS only)",
                                    "standardCost": 155,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 35,
                                    "description": "Miscellaneous One",
                                    "standardCost": 0,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 36,
                                    "description": "Miscellaneous Two",
                                    "standardCost": 0,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 37,
                                    "description": "Miscellaneous Three",
                                    "standardCost": 0,
                                    "costToTraveler": null,
                                    "quantity": 0
                                }
                            ],
                            "moveInDate": "2020-10-13T23:59:59",
                            "moveOutDate": "2021-01-15T23:59:59",
                            "standardMinPayRate": null,
                            "standardNewGradPayRate": null,
                            "standardTLAMinPayRate": null,
                            "standardTLANewGradPayRate": null,
                            "standardTeletherapy": null,
                            "isAlliedTrue": false,
                            "isAssignmentSplit": false
                        }
                    ]
                },
                {
                    "placementId": 8441575,
                    "bookingPeriodId": 379,
                    "scenarioId": 712,
                    "scenarioName": "Scenario 2",
                    "scenarioStatusId": 1,
                    "scenarioStatus": "Pending",
                    "tla": false,
                    "createdUserId": 15568,
                    "createdUserFirst": "Anil",
                    "createdUserLast": "Bhasi",
                    "createdDateAt": "2024-10-24T03:39:54.83",
                    "updatedUserId": 15568,
                    "updatedUserFirst": "Anil",
                    "updatedUserLast": "Bhasi",
                    "updatedDateAt": "2024-10-24T03:39:55.087",
                    "grossMargin": null,
                    "grossProfit": null,
                    "negotiatedContributionMargin": null,
                    "approvedUserId": null,
                    "approvedUserFirst": null,
                    "approvedUserLast": null,
                    "approvedDateAt": null,
                    "approvedReasonId": null,
                    "verifiedUserId": null,
                    "verifiedUserFirst": null,
                    "verifiedUserLast": null,
                    "verifiedDateAt": null,
                    "verifiedReasonId": null,
                    "notes": "",
                    "payCycleStartDayNum": 1,
                    "payCycleStartDay": "Sunday",
                    "payCycleEndDayNum": 7,
                    "payCycleEndDay": "Saturday",
                    "isPerDiemValuesValid": true,
                    "interimPayPackageTimeOffId": null,
                    "assignment": {
                        "timeOffs": [],
                        "travel": {
                            "arrivingTravel": null,
                            "arrivalAmountPerMile": null,
                            "endingTravel": null,
                            "endingAmountPerMile": null,
                            "interimTravel": null,
                            "interimAmountPerMile": null,
                            "amnFlight": null,
                            "amnRentalCar": null
                        },
                        "payPackageDetailsValues": []
                    },
                    "timestamp": "0x00000001CF5F794F",
                    "isDefaultScenario": true,
                    "isMostRecentBookingPeriod": true,
                    "splits": [
                        {
                            "placementId": 8441575,
                            "bookingPeriodId": 379,
                            "scenarioId": 712,
                            "splitId": 805,
                            "effectiveStartDate": "2020-10-15T23:59:59",
                            "effectiveEndDate": "2021-01-13T23:59:59",
                            "payCycleStartDayNum": 1,
                            "payCycleStartDay": "Sunday",
                            "payCycleEndDayNum": 7,
                            "payCycleEndDay": "Saturday",
                            "splitStartDayNum": 5,
                            "splitStartDay": "Thursday",
                            "splitEndDayNum": 7,
                            "splitEndDay": "Wednesday",
                            "isPerDiemValuesValid": true,
                            "billRate": 58.55,
                            "overtime": 0,
                            "holiday": 0,
                            "callback": 0,
                            "billGuaranteedHours": 40,
                            "billAmountPerMile": 0,
                            "payAmountPerMile": 0.67,
                            "splitPlacementId": null,
                            "housingCoPay": null,
                            "lodgingPerDiem": 101.26027,
                            "standardFurniture": null,
                            "housingTypeId": 1,
                            "housingType": "No Housing",
                            "earlyMoveInDays": null,
                            "earlyMoveInDaysWaived": null,
                            "earlyMoveInCostPerDay": null,
                            "lateMoveOutDays": null,
                            "lateMoveOutDaysWaived": null,
                            "lateMoveOutCostPerDay": null,
                            "mealPerDiem": 50,
                            "cellPhoneStipend": 1,
                            "tlaMealAllowance": 30,
                            "tlaCarAllowance": 50,
                            "tlaShiftCompletionBonus": null,
                            "shiftId": 1,
                            "shift": "12 D",
                            "hoursPerWeek": 36,
                            "hoursPerShift": 12,
                            "healthInsuranceTypeId": 1,
                            "healthInsuranceType": "Accepted",
                            "isWaitingPeriodBenefit": false,
                            "tlaCellPhoneStipend": 1,
                            "vms": 6,
                            "other": 1.87,
                            "billDoubletimeRate": 0,
                            "billOvertimeFactor": 1,
                            "billCallBackFactor": 0,
                            "billDoubletimeFactor": 1,
                            "billHolidayFactor": 0.22,
                            "billOnCallRate": 7,
                            "billCharge": 5,
                            "billPreceptor": 0,
                            "orientationHours": 12,
                            "isVoidOrientationHours": null,
                            "payRate": 17.29,
                            "minPayRate": 17.29,
                            "payOvertimeFactor": 1.5,
                            "payCallBackFactor": 0,
                            "payDoubletimeFactor": 2,
                            "payHolidayFactor": 0.3,
                            "payOnCallRate": 3.5,
                            "payGuaranteedHours": 0,
                            "payCharge": 19.78,
                            "payPreceptor": 0,
                            "csfSupervisorCosts": 0,
                            "additionalCostMiscellaneousAmount": null,
                            "additionalCostMiscellaneousDescription": null,
                            "furnitureCoPay": null,
                            "isEarlyMoveIn": null,
                            "isLateMoveOut": null,
                            "earlyMoveInDate": null,
                            "lateMoveOutDate": null,
                            "rentCost": null,
                            "utilities": null,
                            "rentOverrideNot": null,
                            "miscellaneousFurnitureDescription": null,
                            "orientationFactor": 1,
                            "orientationRate": 0,
                            "orientationOverrideUserId": null,
                            "orientationOverrideFirst": null,
                            "orientationOverrideLast": null,
                            "orientationOverrideDate": null,
                            "standardFurnitureOriginal": null,
                            "utilitiesOriginal": null,
                            "rentCostOriginal": null,
                            "furnitureCosts": [
                                {
                                    "id": 19,
                                    "description": "Sofa bed",
                                    "standardCost": 20,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 20,
                                    "description": "TV Stand",
                                    "standardCost": 0,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 22,
                                    "description": "TV - 25 inch",
                                    "standardCost": 30,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 23,
                                    "description": "Extra TV Stand",
                                    "standardCost": 10,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 24,
                                    "description": "Microwave",
                                    "standardCost": 10,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 25,
                                    "description": "DVD Player",
                                    "standardCost": 15,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 26,
                                    "description": "Computer Desk/Chair",
                                    "standardCost": 40.5,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 28,
                                    "description": "Recliner",
                                    "standardCost": 40,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 29,
                                    "description": "Queen Size Bed",
                                    "standardCost": 0,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 30,
                                    "description": "Twin Beds (2)",
                                    "standardCost": 20,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 31,
                                    "description": "King Size Bed",
                                    "standardCost": 20,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 38,
                                    "description": "Additional Bedroom Set",
                                    "standardCost": 75,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 32,
                                    "description": "Washer/Dryer",
                                    "standardCost": 65,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 33,
                                    "description": "Vacuum",
                                    "standardCost": 23,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 34,
                                    "description": "Housewares Package (free to TTS only)",
                                    "standardCost": 155,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 35,
                                    "description": "Miscellaneous One",
                                    "standardCost": 0,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 36,
                                    "description": "Miscellaneous Two",
                                    "standardCost": 0,
                                    "costToTraveler": null,
                                    "quantity": 0
                                },
                                {
                                    "id": 37,
                                    "description": "Miscellaneous Three",
                                    "standardCost": 0,
                                    "costToTraveler": null,
                                    "quantity": 0
                                }
                            ],
                            "moveInDate": "2020-10-13T23:59:59",
                            "moveOutDate": "2021-01-15T23:59:59",
                            "standardMinPayRate": null,
                            "standardNewGradPayRate": null,
                            "standardTLAMinPayRate": null,
                            "standardTLANewGradPayRate": null,
                            "standardTeletherapy": null,
                            "isAlliedTrue": false,
                            "isAssignmentSplit": true
                        }
                    ]
                }
            ]
        }
    ]))
}

export  {responseV2 as response}

