const marginDetailsTestData = [
  {
    placementId: 12345,
    placementStartDate: new Date('2024-10-01'), // Convert string to Date
    placementEndDate: new Date('2025-03-31'), // Convert string to Date
    placementDuration: 182,
    facility: {
      facilityId: 67890,
      facilityName: 'General Hospital',
      facilityAddress1: '123 Main St',
      facilityAddress2: 'Suite 200',
      facilityState: 'CA',
      facilityCity: 'Los Angeles',
      facilityZip: 90001,
      facilityLongitude: -118.2437,
      facilityLatitude: 34.0522,
      facilityCountry: 'USA',
      facilityRegionId: 1,
    },
    travelerId: 54321,
    candidateNameFirst: 'John',
    candidateNameMiddle: 'D.',
    candidateNameLast: 'Doe',
    candidateNameGoesBy: 'Johnny',
    brandId: 101,
    brand: 'Healthcare Staffing',
    orderId: 55555,
    disciplineId: 202,
    specialtyId: 303,
    subspecialtyId: 404,
    shiftId: 1,
    shift: 'Day Shift',
    isScenarioExtention: true,
    isMostRecentBookingPeriod: true,
    extensionNumber: 2,
    isExtensionOfPriorPlacement: true,
    extensionOfPriorPlacementId: 11111,
    bookingPeriodId: 22222,
    bookingPeriodStartDate: new Date('2024-10-01'), // Convert string to Date
    bookingPeriodEndDate: new Date('2025-03-31'), // Convert string to Date
    bookingPeriodDuration: 182,
    packageName: 'Standard Package',
    recruiter: {
      employeeId: 6789,
      firstName: 'Jane',
      lastName: 'Smith',
      phoneNumber: '555-1234',
      email: 'jane.smith@company.com',
    },
    scenarios: [
      {
        placementId: 12345,
        bookingPeriodId: 22222,
        scenarioId: 1,
        scenarioName: 'Scenario A',
        scenarioStatusId: 1,
        scenarioStatus: 'Approved',
        tla: true,
        createdUserId: 10101,
        createdUserFirst: 'Alice',
        createdUserLast: 'Johnson',
        createdDateAt: new Date('2024-09-15'), // Convert string to Date
        updatedUserId: 10102,
        updatedUserFirst: 'Bob',
        updatedUserLast: 'Williams',
        updatedDateAt: new Date('2024-09-20'), // Convert string to Date
        grossMargin: 5000,
        grossProfit: 3000,
        negotiatedContributionMargin: '15%',
        approvedUserId: 10103,
        approvedUserFirst: 'Carol',
        approvedUserLast: 'Taylor',
        approvedDateAt: new Date('2024-09-25'), // Convert string to Date
        notes: 'Scenario approved with standard rates.',
        splits: [
          {
            placementId: 12345,
            bookingPeriodId: 22222,
            scenarioId: 1,
            splitId: 1,
            effectiveStartDate: new Date('2024-10-01'), // Convert string to Date
            effectiveEndDate: new Date('2024-12-31'), // Convert string to Date
            billRate: 100,
            overtime: 150,
            holiday: 200,
            billGuaranteedHours: 40,
            billAmountPerMile: 0.5,
            payAmountPerMile: 0.3,
            housingCoPay: 300,
            lodgingPerDiem: 1500,
            mealPerDiem: 500,
            cellPhoneStipend: 50,
            shiftId: 1,
            shift: 'Day Shift',
            hoursPerWeek: 40,
            hoursPerShift: 8,
            furnitureCosts: [
              {
                id: 1,
                description: 'Standard Bed',
                standardCost: 200,
                costToTraveler: 50,
                quantity: 1,
              },
              {
                id: 2,
                description: 'Sofa',
                standardCost: 300,
                costToTraveler: 75,
                quantity: 1,
              },
            ],
            payRate: 50,
            payOvertimeFactor: 1.5,
            payHolidayFactor: 2.0,
            isAlliedTrue: true,
            minPayRate: 11,
            standardMinPayRate: 21,
            standardNewGradPayRate: 113,
            standardTLAMinPayRate: 45,
            standardTLANewGradPayRate: 35,
            standardTeletherapy: 20,
          },
        ],
      },
    ],
  },
];

export { marginDetailsTestData };
